import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>DongFlix</title>
        <link rel="icon" href="favico.ico" />
      </head>

      <body className={inter.className}>
        <Link href={"/"} className="Link">
          <h1 className="main-title">DONGFLIX</h1>
        </Link>
        {children}
        <h5 className="main-title">DONGFLIX</h5>
        <h5 className="main-title">Made by LDH, 2023</h5>
      </body>
    </html>
  );
}
