/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import MainLinks from "./list/MainLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>DongFlix</title>
        <link rel="icon" href="favico.ico" />
      </head>

      <body className={inter.className}>
        <div className="main-logo-container">
          <Link href={"/"} className="Link">
            <img src="logo.png" alt="DONGFLIX" className="main-logo" />
          </Link>
        </div>

        <MainLinks />
        {children}
        <hr />
        <h5 className="main-footer">
          Copyright ⓒ 2023 DONGFLIX. All rights reserved.
        </h5>
      </body>
    </html>
  );
}
